/** @type {import('@storybook/html-vite').StorybookConfig} */
export default {
  stories: ['../stories/**/*.stories.js'],
  framework: { name: '@storybook/html-vite', options: {} },
  // `build/` is gitignored and regenerated by `npm run build:tokens`, which the
  // storybook scripts run first. Nothing here reads `tokens/` directly — the
  // resolved JSON emitted by the pipeline is the only source the stories see.
};
